name: econ-dl
channels:
  - defaults
dependencies:
  - python=3.11
  - tensorflow=2.19.1=cuda124py311ha1f05a4_200
  - numpy
  - tensorboard
  - matplotlib
  - seaborn
  - scipy
  - pytest
  - black
  - flake8
  - pip
  - pip:
      - tensorflow-probability==0.25.0
      - tf-keras==2.19.0
      - cma
